### ISSUE TITLE
Leon don't want to talk french, angry omelette du fromage

### ISSUE THREAD

**Issue by gnouf1** [leon-ai/leon#102] opened 2019-06-03 00:43 UTC
### Specs

- Leon version: beta 3
- OS (or browser) version: Windows 10 but Leon on WSL Ubuntu 18
- Node.js version: 11
- Complete "npm run check" output:
```
---

.: CHECKING :.

➡ /bin/sh -c node --version
✔ v11.15.0

➡ /bin/sh -c npm --version
✔ 6.7.0

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /home/user/leon-dev/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.6.7

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 8, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
```

### Actual Behavior
When i talk whit Leon in french it's crash

### How Do We Reproduce?
Talk french with Leon :p

### Extra (like a sample repo to reproduce the issue, etc.)
```
(node:1042) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'split' of undefined
    at Nlu.process (/home/user/leon-dev/server/dist/core/nlu.js:103:45)
    at processTicksAndRejections (internal/process/task_queues.js:86:5)
(node:1042) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1042) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Comment by louistiti** [comment] 2019-06-05 23:23
Hello @gnouf1,

Thanks for opening that issue. What query are you doing in French? I'm not able to reproduce that bug for the moment.

**Comment by gnouf1** [comment] 2019-06-06 00:00
I tried "Bonjour"
But none package work :/

**Comment by louistiti** [comment] 2019-06-06 00:05
In your `.env` file, did you correctly set the `LEON_LANG` to `fr-FR`?

**Comment by gnouf1** [comment] 2019-06-06 00:34
Yes 

```
✔ The current env is production
✔ The current version is 1.0.0-beta.3
✔ The current language is fr-FR
✔ The current time zone is Africa/Lagos
✔ Collaborative logger enabled
✔ Server is available at 192.168.56.1:1337
```

**Comment by louistiti** [comment] 2019-06-06 15:53
Have you tried to create a new folder, clone the `develop` repository in it and rerun from there?

Also, please try with the basic setup without a specific host (just by using the default value `localhost`) to see if that changes something.

**Comment by gnouf1** [comment] 2019-06-07 22:44
I try on an different computer it's do same things :/

**Comment by louistiti** [comment] 2019-06-08 04:18
What OS are you running on this other computer?

**Comment by gnouf1** [comment] 2019-06-08 08:58
Ubuntu

**Comment by louistiti** [comment] 2019-06-08 15:06
Ubuntu under Windows or a complete dedicated one?

Because I've tried several times to reproduce that, but it's always working here.

**Comment by gnouf1** [comment] 2019-06-08 16:17
I tried on a new leon installation on my WSL and on an new installation on fully ubuntu one

**Comment by louistiti** [comment] 2019-06-08 23:22
I use Ubuntu myself to work on Leon and I see none of these errors.

On your "fully" Ubuntu OS, have you completely pulled and install a whole new Leon? Could you please tell me which Ubuntu version it is and paste the result of the `npm run check` command?

**Comment by gnouf1** [comment] 2019-06-08 23:57
I pulled and install a full new and clean Leon beta 1.0.0 3

npm run check :
```
.: CHECKING :.

➡ /bin/sh -c node --version
✔ v11.0.0

➡ /bin/sh -c npm --version
✔ 6.4.1

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /home/theo/Documents/leon2/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.7.1

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 38, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
❗ Amazon Polly TTS is not yet configured

➡ Google Cloud TTS/STT
❗ Google Cloud TTS/STT is not yet configured

➡ Watson TTS
❗ Watson TTS is not yet configured

➡ Offline TTS
❗ Cannot find bin/flite/flite. You can setup the offline TTS by running: "npm run setup:offline-tts"

➡ Watson STT
❗ Watson STT is not yet configured

➡ Offline STT
❗ Cannot find bin/deepspeech/lm.binary. You can setup the offline STT by running: "npm run setup:offline-stt"

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
❗ Amazon Polly text-to-speech
❗ Google Cloud text-to-speech
❗ Watson text-to-speech
❗ Offline text-to-speech
❗ Google Cloud speech-to-text
❗ Watson speech-to-text
❗ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
```

**Comment by louistiti** [comment] 2019-06-09 00:19
Unfortunately I'm not able to reproduce that error although I have the same specs as you.

```
.: CHECKING :.

➡ /bin/sh -c node --version
✔ v11.15.0

➡ /bin/sh -c npm --version
✔ 6.7.0

➡ /bin/sh -c pipenv --version
✔ pipenv, version 2018.11.26

➡ /bin/sh -c pipenv --where
✔ /home/louis/Workspace/leon/bridges/python

➡ /bin/sh -c pipenv run python --version
✔ Python 3.7.1

➡ /bin/sh -c pipenv run python bridges/python/main.py scripts/assets/query-object.json
✔ {"package": "leon", "module": "randomnumber", "action": "run", "lang": "en", "input": "Give me a random number", "entities": [], "output": {"type": "end", "codes": ["success"], "speech": 8, "options": {}}}

➡ Classifier state
✔ Found and valid

➡ Amazon Polly TTS
✔ Configured

➡ Google Cloud TTS/STT
✔ Configured

➡ Watson TTS
✔ Configured

➡ Offline TTS
✔ Found Flite at bin/flite/flite

➡ Watson STT
✔ Configured

➡ Offline STT
✔ Found DeepSpeech language model at bin/deepspeech/lm.binary

---

.: REPORT :.

➡ Here is the diagnosis about your current setup
✔ Run
✔ Run modules
✔ Reply you by texting
✔ Amazon Polly text-to-speech
✔ Google Cloud text-to-speech
✔ Watson text-to-speech
✔ Offline text-to-speech
✔ Google Cloud speech-to-text
✔ Watson speech-to-text
✔ Offline speech-to-text

✔ Hooray! Leon can run correctly
➡ If you have some yellow warnings, it is all good. It means some entities are not yet configured
```

![Peek 2019-06-09 08-15](https://user-images.githubusercontent.com/1731544/59153582-0926b980-8a8f-11e9-91c5-cd9164d192e5.gif)

Is that possible for you to share a GIF of the web app and console?

**Comment by gnouf1** [comment] 2019-06-09 00:30
I share for my ubuntu WSL :
[https://gyazo.com/1913d4d7e735e0a4d2393b39c22485ea](url)

**Comment by gnouf1** [comment] 2019-06-09 00:40
And on my fully ubuntu :
![mon-super-gif-de-test](https://user-images.githubusercontent.com/12630623/59153666-ee891c00-8a5f-11e9-99b9-7211a7b54f62.gif)

**Comment by louistiti** [comment] 2019-06-09 00:43
Thanks for sharing.

I've created a Discord server just now. Would you mind [joining it](https://discord.gg/MNQqqKg) so we can talk further?

Explanations will be posted here if that is fixed.

**Comment by louistiti** [comment] 2019-06-09 01:10
After digging into some debugging, the issue is fixed quite strangely.

A simple new build (`npm run build` and `npm start`) fixed it. I suppose it was due to a change in the code that was not update or something similar.

I'll close this issue as it is now working.

**Closed by louistiti** 2019-06-09 01:10 UTC
Labels: bug
